### ISSUE TITLE
Some villages are not being returned

### ISSUE THREAD

**Issue by fredshema** [knowbee/rwanda#10]
I have noticed that you added this functionality to your code 
```javascript
const formatInput = name => {
  return name && name.length > 2
    ? name.charAt(0).toUpperCase() + name.substring(1).toLowerCase()
    : undefined;
}
```
The issue here is for cells which are numbered for example `Rukiri I` and `Rukiri II` from `Remera,Gasabo`. They are transformed into `Rukiri i` and `Rukiri ii` but their data have object properties of `Rukiri I` and `Rukiri II` resulting in return of `undefined` when you call `Cell("Kigali","Gasabo","Remera","Rukiri I")`

**Comment by knowbee** [comment]
Oooh i see, It looks like i didn't pay attention to that use case.but also notice the error you are mentioning is seen when you call `Village("Kigali","Gasabo","Remera","Rukiri I")` not `Cell("Kigali","Gasabo","Remera","Rukiri I")`. Fixing it right now, thanks for opening the issue👏👏
