### ISSUE TITLE
Some village name is misspelled

### ISSUE THREAD

**Issue by fredshema** [knowbee/rwanda#8]
#### A village in nyabisindu is not written well.
* input:    ` Village("Kigali","Gasabo","Remera","Nyabisindu")` 

* output: ` ["Amarembo I", "Amarembo Il", "Gihogere", "Kagara", "Kinunga",     "Nyabisindu", "Rugarama"]`

```javascript
 Issue: String("Amarembo Il").toUpperCase()
```

* outcome : `AMAREMBO IL `

* expexted : `AMAREMBO II`

**Comment by knowbee** [comment]
Thanks for opening this issue Fred, nice catch. fixing it right now😉

**Comment by descholar-ceo** [comment]
vvvv###rre
